apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: customers
spec:
  params:
    - name: repo-url
      type: string
      description: The Git repository URL to clone
    - name: revision
      type: string
      description: The Git revision to clone
      default: master
  workspaces:
    - name: pipeline-workspace
  tasks:
    - name: clone
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: pipeline-workspace
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.revision)
        - name: subdirectory
          value: customers
        - name: deleteExisting
          value: "true"
    - name: lint
      taskRef:
        name: lint
      runAfter:
        - clone
      workspaces:
        - name: source
          workspace: pipeline-workspace
    - name: test
      taskRef:
        name: test
      runAfter:
        - clone
      workspaces:
        - name: source
          workspace: pipeline-workspace
    - name: build
      taskRef:
        name: buildah
      runAfter:
        - lint
        - test
      workspaces:
        - name: source
          workspace: pipeline-workspace
      params:
        - name: IMAGE
          value: image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/customers:$(tasks.clone.results.commit)
        - name: CONTEXT
          value: customers